name: "Shopping Application"

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      packer_version: "1.9.4"

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Setup packer"
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run: "packer init ./packer/main.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./packer/main.pkr.hcl"
       
       - name: Run `packer build`
        id: build
        run: "packer build ./packer/main.pkr.hcl"



